force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order1</fullName>
            </value>
            <value>
                <fullName>Order2</fullName>
            </value>
            <value>
                <fullName>Consult1</fullName>
            </value>
            <value>
                <fullName>Colsultt2</fullName>
            </value>
            <value>
                <fullName>Solicitude1</fullName>
            </value>
            <value>
                <fullName>Solicitude2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Integration_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Id__c</fullName>
    <label>Integration Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Auto Owner Assign</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Sub_Area__c</fullName>
    <label>Sub Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SubOrder11</fullName>
            </value>
            <value>
                <fullName>SubOrder12</fullName>
            </value>
            <value>
                <fullName>SubOrder21</fullName>
            </value>
            <value>
                <fullName>SubOrder22</fullName>
            </value>
            <value>
                <fullName>SubConsult11</fullName>
            </value>
            <value>
                <fullName>SubConsult12</fullName>
            </value>
            <value>
                <fullName>SubConsult21</fullName>
            </value>
            <value>
                <fullName>SubConsult22</fullName>
            </value>
            <value>
                <fullName>SubSolicitude11</fullName>
            </value>
            <value>
                <fullName>SubSolicitude12</fullName>
            </value>
            <value>
                <fullName>SubSolicitude21</fullName>
            </value>
            <value>
                <fullName>SubSolicitude22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Created</fullName>
            </value>
            <value>
                <fullName>Document Sent</fullName>
            </value>
            <value>
                <fullName>Validation Bio Failed</fullName>
            </value>
            <value>
                <fullName>Validation Bio Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Consult</fullName>
            </value>
            <value>
                <fullName>Solicitud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PublishOrder.cls
global class PublishOrder {

    webservice static void UpdateSR(String SRnum, Integer IntId,String Status,String SubStatus)
    {
       
        
        
        try
        {
        Service_Request__c SRT;
        SRT = [Select Id from Service_Request__c where Name=: SRnum];
        SRT.Status__c = Status;
        SRT.Sub_Status__c = SubStatus;
        Update SRT;
        }
       
        catch(Exception e)
        {
            system.debug('asdasdasdasdas');
			Service_Request__c SRT2 = new Service_Request__c(Account__c = '0017F00000bobVpQAI',Type__c = 'Order',Area__c = 'Order1',Sub_Area__c = 'SubOrder12');
            insert SRT2; 
        }
          


            
     //   IF(IntId!=0)
      /*  {
            Service_Request__c SRT = [Select Id from Service_Request__c where Integration_Id__c=: IntId];
            SRT.Status__c = Status;
            SRT.Sub_Status__c = SubStatus;
            Update SRT;
    //    }*/
       
    }
    
}