force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/for_delete_c__c.field-meta.xml
<CustomField>
    <fullName>for_delete_c__c</fullName>
    <defaultValue>false</defaultValue>
    <label>For Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CleanCreatedSR.cls
@RestResource(urlMapping = '/executebatch/*')
global class CleanCreatedSR {
///services/apexrest/executebatch -- URL in WOrkbench
    global class RequestWrapper {
        
    }
    // RESPONSE PARAMETERS 
    global class ResponseWrapper {
        //Select for_delete_c__c,name from Service_Request__c where for_delete_c__c = true
    }
    
@HttpGet
  /*  global static ResponseWrapper executeBatch() 
    {
        DeleteUserCreatedRecordsBATCH obj=new DeleteUserCreatedRecordsBATCH();
        Database.executeBatch(obj);
        return null;
    }*/

    global static ResponseWrapper executeQueue() 
    {
      
        return null;
    }

}