force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Auto Owner Assign</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoOwnerAssignment.cls
public class AutoOwnerAssignment {
	 @InvocableMethod
  	public static void AutoAssignment(List<Id> SrId)
    {
		
      // User[] AssignedUsrs = [Select Id from User where Id IN (Select Owner__c from Service_Request__c where Owner__c != null)];
  	   User[] UnAssignedUsrs = [Select Id from User where Id NOT IN (Select Owner__c from Service_Request__c where Owner__c != null and Status__c !='Closed') and UserRoleId != null];
		system.debug(UnAssignedUsrs.size());
        String UserEmail;
        String UserName;
        String SRNum;
        
        If(UnAssignedUsrs.size()==0)
      	 {
           AggregateResult[] SR = [Select Count(Id)am, Owner__c from Service_Request__c where Owner__c != '' and Status__c !='Closed' group by Owner__c ORDER BY Count(Id)];
           String str = String.valueOf(SR[0].get('Owner__c'));
            Service_Request__c SRT = [Select Owner__c,Name from Service_Request__c where Id =: SrId ];
            SRT.Owner__c = str;
            SRNum  = SRT.Name;
            User usr = [Select Name,Email from user where Id =: str]  ;   
            UserName = usr.Name;
            UserEmail = usr.Email;
            update SRT;
     	 }
        else
        {
            String str2 = String.valueOf(UnAssignedUsrs[0].get('Id'));
            Service_Request__c SRT = [Select Owner__c from Service_Request__c where Id =: SrId ];
            SRT.Owner__c = str2;
            SRNum  = SRT.Name;
            User usr = [Select Name,Email from user where Id =: str2]  ;  
            UserName = usr.Name;
            UserEmail = usr.Email;
            update SRT;
        }
        
        String EmailSubject = 'SR:'+SRNum+'has been assigned to you!';
        String EmailBody = 'Hi' +UserName+',\nSR:'+SRNum+' has been assigned to you. Please check.\nRegards,\nEntel.';
		EmailManager.sendMail(UserEmail,EmailSubject,EmailBody);
        
       
     
        
        
       
    }
    
}