force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Integration_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Id__c</fullName>
    <label>Integration Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Auto Owner Assign</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Created</fullName>
            </value>
            <value>
                <fullName>Document Sent</fullName>
            </value>
            <value>
                <fullName>Validation Bio Failed</fullName>
            </value>
            <value>
                <fullName>Validation Bio Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WSController1.cls
public class WSController1 {
    
    private Final Service_Request__c SRT;
   // public Service_Request__c SRT ( get; set; }
   Double result;
    public WSController1 (ApexPages.StandardController con){
        this.SRT = (Service_Request__c)con.getRecord();
    }
	
    
   public Double getdoAdd()
    
    {
        

calculatorServices.CalculatorImplPort calculator = new  calculatorServices.CalculatorImplPort();
        
  // Service_Request__c test12  = new Service_Request__c();
 String x = SRT.Name;
Double myDecimal = Double.valueOf(x);
Double y = 2.0;
result = calculator.doAdd(myDecimal,y);
       	
      
         return result;

    }
    
 //   PageReference returnPage = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));  
    public PageReference udpateSR()
    {
      //Pagereference pg =  new Pagereference('/apex/LastSRPage'); 
     // PageReference returnPage = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));  
     String theId = SRT.Id;
     PageReference returnPage = new PageReference('/' + theId);
	returnPage.setRedirect(true);
          SRT.Status__c = 'In Progress';
        SRT.Sub_Status__c = 'Order Created';
        SRT.Integration_Id__c = result;	
        update SRT;
        return returnPage;
       
       
    }    
    
   
   
    
    
}