force-app/main/default/objects/Question_Set__c/Question_Set__c.object-meta.xml
<CustomObject>
    <label>Question Set</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Question Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionare__c/Questionare__c.object-meta.xml
<CustomObject>
    <label>Questionare</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Questionare Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionare__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Questionares</relationshipLabel>
    <relationshipName>Questionares</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Questionare__c/fields/Question_Set__c.field-meta.xml
<CustomField>
    <fullName>Question_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Set</label>
    <referenceTo>Question_Set__c</referenceTo>
    <relationshipLabel>Questionares</relationshipLabel>
    <relationshipName>Questionares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuestionareController.cls
public class QuestionareController {
    
    private Final Service_Request__c QRT;
     //List<String> twtt =new list<String>();
    public List<String> twtt{get;set;}
  //  public String[] Answer = new String[2] {get;set;};
    public String[] Answer{get;set;}
    public QuestionareController (ApexPages.StandardController con){
        this.QRT = (Service_Request__c)con.getRecord();
    }
    
    //private Final Service_Request__c
     
    public List<String> getQuestions()
    {
        //String Acc = new String();
        Service_Request__c ActId = [Select Account__c from Service_Request__c where Id =: QRT.Id ];
        String Acc = ActId.Account__c;
      // String Acc = '0017F00000bobVpQAI';
        List<Questionare__c> Qnare = [Select Question_Set__c from Questionare__c where Account__c = : Acc];
		integer ste = Qnare.size();
        List<Question_Set__c> qe;
        List<Question_Set__c> asdasd; 
        twtt = new List<String>();
       
        String abcs;
        for(Integer i=0;i<Qnare.size();i++)
        {
            Questionare__c tra = Qnare[i];           
            asdasd = [Select Name from Question_Set__c where Id = : tra.Question_Set__c];
            abcs = asdasd[0].Name;
		    twtt.add(abcs);
        }
         return(twtt);

	}
    public void CheckforCorrectness()
    {
     // String strPageNumber = ApexPages.CurrentPage().getParameters().get('prmPageNumber');
     //Integer xis = Answer.size();
    // Answer = 'asdadsasd';
       system.debug(Answer);    
    }
    
 
}