force-app/main/default/objects/Account/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <customHelpPage>PlanPage</customHelpPage>
    <label>Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/SMS__c.field-meta.xml
<CustomField>
    <fullName>SMS__c</fullName>
    <label>SMS %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Voice__c.field-meta.xml
<CustomField>
    <fullName>Voice__c</fullName>
    <label>Voice %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ChoosePlan.cls
public class ChoosePlan {
   
     public Final Service_Request__c SRT;
     public String Plan {get; set;}
     
     public ChoosePlan (ApexPages.StandardController con){
        this.SRT = (Service_Request__c)con.getRecord();
    }
    
    public List<Plan__c> Plan1 {get
    {
       /* String SrId = SRT.Id ;
        Service_Request__c SRActId = [Select Account__c from Service_Request__c where Id =: SrId];
        String ActId = SRActId.Account__c;
        Account AssetId = [Select Asset__c from Account where Id =: ActId];
        String AstId = AssetId.Asset__c;  */   
      //  Audit1 = [SELECT Field,CreatedDate,NewValue,OldValue FROM AssetHistory where Field = 'Prepaid_Balance__c' and Asset.Id =:AstId  ];
        Plan1 = [Select Name,Data__c,SMS__c,Voice__c from Plan__c]; 
      //  system.debug(Audit1);
        return Plan1;
    }
	set;}
    
    public void UpdAst()
    {
        system.debug(Plan);
        String mulId = Plan.substring(0,Plan.length()-3);
        system.debug(mulId);
      if(Plan != null && Plan != '' )
       {
            String SrId = SRT.Id ;
            Service_Request__c SRActId = [Select Account__c from Service_Request__c where Id =: SrId];
            String ActId = SRActId.Account__c;
            Account AssetId = [Select Asset__c from Account where Id =: ActId];
            String AstId = AssetId.Asset__c;     
            Asset Ast1 = [SELECT Id,Plan__c from Asset where Id =:AstId  ];
            Ast1.Plan__c = mulId;
            update Ast1;
        } 
        
            }
}