force-app/main/default/objects/Account/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HistoryController.cls
public class HistoryController {
    
     public Final Service_Request__c SRT;
     
     public HistoryController (ApexPages.StandardController con){
        this.SRT = (Service_Request__c)con.getRecord();
    }
    
    public List<AssetHistory> Audit1 {get
    {
        String SrId = SRT.Id ;
        Service_Request__c SRActId = [Select Account__c from Service_Request__c where Id =: SrId];
        String ActId = SRActId.Account__c;
        Account AssetId = [Select Asset__c from Account where Id =: ActId];
        String AstId = AssetId.Asset__c;     
        Audit1 = [SELECT Field,CreatedDate,NewValue,OldValue FROM AssetHistory where Field = 'Prepaid_Balance__c' and Asset.Id =:AstId  ];
        system.debug(Audit1);
        return Audit1;
    }
	set;}
    
   /* public List<AssetHistory> GetHistory()
    {
        String SrId = SRT.Id ;
        Service_Request__c SRActId = [Select Account__c from Service_Request__c where Id =: SrId];
        String ActId = SRActId.Account__c;
        Account AssetId = [Select Asset__c from Account where Id =: ActId];
        String AstId = AssetId.Asset__c;      
        Audit1 = [SELECT Field,NewValue,OldValue FROM AssetHistory where Field = 'Prepaid_Balance__c' and Asset.Id =:AstId  ];
        system.debug(Audit1);
        return Audit1;
   */ //}

}