force-app/main/default/objects/Account/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <label>Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Price_List_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price List Item</label>
    <referenceTo>Price_List_Item__c</referenceTo>
    <relationshipLabel>&lt;Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <formula>Price_List_Item__r.Produkt__r.Name</formula>
    <label>ProductName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Produkt__c.field-meta.xml
<CustomField>
    <fullName>Produkt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produkt</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>&lt;Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Rate_Code__c.field-meta.xml
<CustomField>
    <fullName>Rate_Code__c</fullName>
    <formula>Price_List_Item__r.Rate_Code__c</formula>
    <label>Rate Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>&lt;Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Cost__c.field-meta.xml
<CustomField>
    <fullName>Service_Cost__c</fullName>
    <formula>Price_List_Item__r.Price__c</formula>
    <label>Service Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Waiting for Serial Number</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <label>Price List</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_List_Item__c/Price_List_Item__c.object-meta.xml
<CustomObject>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Price List Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_List_Item__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Price List Items</relationshipLabel>
    <relationshipName>Price_List_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price_List_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Produkt__r.Name</formula>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_List_Item__c/fields/Produkt__c.field-meta.xml
<CustomField>
    <fullName>Produkt__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produkt</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Price List Items</relationshipLabel>
    <relationshipName>Price_List_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_List_Item__c/fields/Rate_Code__c.field-meta.xml
<CustomField>
    <fullName>Rate_Code__c</fullName>
    <formula>Produkt__r.Part__c</formula>
    <label>Rate Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerPortalController.cls
public class CustomerPortalController {
    
    public Final Sales_Order__c SO;
    public Sales_Order__c SalesOrder {get; set;}
    public Account Acct {get; set;}
    //public List<Price_List_Item__c> PriceListItem {get; set;}
    public List<Order_Item__c> OrderListItem {get; set;}
    
     public CustomerPortalController (ApexPages.StandardController con)
     {
        this.SO = (Sales_Order__c)con.getRecord();
        SalesOrder = [Select Account__c,Contract_Start_Date__c,Contract_End_Date__c,Name,Price_List__C from Sales_Order__c where Id =: SO.Id];
        system.debug(SalesOrder);
        String AccountId = SalesOrder.Account__c;
        system.debug('AccountIs'+SalesOrder);
        Acct = [Select Name,ShippingState,ShippingStreet,ShippingCity,ShippingPostalCode,ShippingCountry,AccountNumber,Contact_Email__c from Account where Id =: AccountId] ;
        system.debug('Acct'+Acct);
        String PriceListId = SalesOrder.Price_List__c;
        system.debug('this.SO'+this.SO);
        //PriceListItem = [Select Product_Name__c,Produkt__c,Rate_Code__c,Start_Date__c,Price__c from Price_List_Item__c where Price_List__c	 =: PriceListId] ;
        OrderListItem = [Select ProductName__c,Service_Cost__c,Rate_Code__c,Start_Date__c,Status__c,End_Date__c from Order_Item__c where Sales_Order__c =: SO.Id] ;
         
         
         
    }
}