force-app/main/default/objects/People__c/People__c.object-meta.xml
<CustomObject>
    <label>People</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/fields/Tour__c.field-meta.xml
<CustomField>
    <fullName>Tour__c</fullName>
    <label>Tour</label>
    <referenceTo>Tour__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <label>Tour</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tour Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AddPeople.cls
public class AddPeople {
  //  private Final People__c QRT;
   // public String Park {get; set;}
    public string People1 {get;set;}
   //  public String banks2SF{get;set;} 
    public List<String> banks{get;set;}
     public String ExpId{get;set;}
    
 //  public List<SelectOption> getPeople1  {get;set;}
 //   public String Answer {get;set;}
 //   String country = null;
/*    public AddPeople(ApexPages.StandardController con)
    {
        this.QRT = (People__c)con.getRecord();
    } */
    
 public List<SelectOption> getPeople1  {get
 {
     
     
       string TourId = 'a0U7F000009cZ4iUAE';
         system.debug('asdasdsa');
     system.debug(ExpId);
     
           //QRT.Tour__c;
       List<People__c> PPL1 = [Select Name from People__c where Tour__c =: TourId];
       // system.debug(PPL1);
        List<SelectOption> options = new List<SelectOption>(); 
        for(Integer i=0;i<PPL1.size();i++)
        {
            options.add(new SelectOption(PPL1[i].Name,PPL1[i].Name));
        }
		return options;        
    }
    set; }  
    //}
    
    Public void  Calculate()
    {
		
    //  Strig test  = Cache.Session.get('ExpId');
          system.debug(Cache.Session.get('ExpId'));
    }
}