force-app/main/default/objects/People__c/People__c.object-meta.xml
<CustomObject>
    <label>People</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/fields/Tour__c.field-meta.xml
<CustomField>
    <fullName>Tour__c</fullName>
    <label>Tour</label>
    <referenceTo>Tour__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <label>Tour</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tour Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AddExpenseTrigger.cls
public class AddExpenseTrigger {
	public Final Tour__c PPL;
    public AddExpenseTrigger (ApexPages.StandardController con){
        this.PPL = (Tour__c)con.getRecord();
    }
    
    public PageReference Trig()
    {      
       // system.debug('YESSSs');
        // People__c test = [Select Tour__c from People__c where Id=:PPL.Id];
        // String TripId = test.Tour__c;
       // system.debug(TripId);
         PageReference pg = new PageReference('/apex/AddExpensePage?TripId='+PPL.Id);  
         pg.getParameters().put('TripId',PPL.Id);
         pg.setRedirect(TRUE);
        return pg;
    }    

}