force-app/main/default/objects/People__c/People__c.object-meta.xml
<CustomObject>
    <label>People</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/fields/Amount_Owed_by_Me__c.field-meta.xml
<CustomField>
    <fullName>Amount_Owed_by_Me__c</fullName>
    <label>Amount Owed by Me</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Tour__c.field-meta.xml
<CustomField>
    <fullName>Tour__c</fullName>
    <label>Tour</label>
    <referenceTo>Tour__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <label>Tour</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tour Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tour_Expense__c/Tour_Expense__c.object-meta.xml
<CustomObject>
    <label>Tour Expense</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tour Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tour_Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Spent Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tour_Expense__c/fields/People__c.field-meta.xml
<CustomField>
    <fullName>People__c</fullName>
    <label>People</label>
    <referenceTo>People__c</referenceTo>
    <relationshipLabel>Tour Expenses</relationshipLabel>
    <relationshipName>Tour_Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AddExp.cls
public class AddExp {
	public Final Tour_Expense__c PPL;
    Public static String ExpId;
   // Public static String TripId{get; set;}
    public Decimal Amt {get; set;}
    public AddExp (ApexPages.StandardController con){
        this.PPL = (Tour_Expense__c)con.getRecord();
    }
    
        public string People1 {get;set;}
    public List<String> banks{get;set;}
    public String TripId;
    
    // public String ExpId{get;set;}    
  
 public List<SelectOption> getPeople1  {get
 {  
      //string TourId = 'a0U7F000009cZ4iUAE';
     TripId = apexpages.currentpage().getparameters().get('TripId');
      system.debug(TripId);
       List<People__c> PPL1 = [Select Name from People__c where Tour__c =: TripId];
        List<SelectOption> options = new List<SelectOption>(); 
        for(Integer i=0;i<PPL1.size();i++)
        {
            options.add(new SelectOption(PPL1[i].Name,PPL1[i].Name));
        }
		return options;        
    }
    set; }  
    
    public PageReference Next()
    {
		insert PPL;  
		ExpId = PPL.Id;
        Amt = PPL.Amount__c;
        
       // system.debug(ExpId);
       
         PageReference pg = new PageReference('/apex/AddingthePeople');     
        //Pagereference pg =  new Pagereference('/apex/AddingthePeople');
       // pg.getParameters().put(ExpId, ExpId);
        return pg;
    }    
    
    Public PageReference Calculate()
    {
        String theId = TripId;
         PageReference returnPage = new PageReference('/' + theId);
        returnPage.setRedirect(true);
        system.debug('banks='+banks);
        system.debug('Amt='+Amt);
		Decimal NumOfMemSelc = banks.size();
        system.debug('NumOfMemSelc='+NumOfMemSelc);
        Decimal AmounttoBeDistributed = Amt/NumOfMemSelc ;
        system.debug('AmounttoBeDistributed='+AmounttoBeDistributed);
        Decimal CurrentowedAmount;
        Decimal NewowedAmount;
        People__c MemberName ;
        for(Integer i=0;i<NumOfMemSelc;i++)
        {
            MemberName = [Select Amount_Owed_by_Me__c from People__c where Name=:banks[i] ];
            system.debug('MemberName='+banks[i]);
            system.debug(banks);
        	CurrentowedAmount = MemberName.Amount_Owed_by_Me__c;
            system.debug('CurrentowedAmount='+CurrentowedAmount);
            if(CurrentowedAmount != null)
            {
                NewowedAmount = CurrentowedAmount+AmounttoBeDistributed;
            }
            else
            {
                NewowedAmount = AmounttoBeDistributed;
            }
            
            system.debug('NewowedAmount='+NewowedAmount);
            MemberName.Amount_Owed_by_Me__c = NewowedAmount;
            update MemberName;
           // 
        }

        return returnPage;
    }
    
}