force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <customHelpPage>PlanPage</customHelpPage>
    <label>Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/SMS__c.field-meta.xml
<CustomField>
    <fullName>SMS__c</fullName>
    <label>SMS %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Voice__c.field-meta.xml
<CustomField>
    <fullName>Voice__c</fullName>
    <label>Voice %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/UpdateBalancesAsset.cls
public class UpdateBalancesAsset {
   @InvocableMethod
     public static void getdoAdd()
    
    {  
     system.debug('kjdakdakjhda');
     Asset Ast = [Select Prepaid_Balance__c,Plan__c,Voice_Balance__c,Data_Balance__c,SMS_Balance__c from Asset where Id =: '123213'];
     Decimal VoiceBal = Ast.Voice_Balance__c;
     Decimal DataBal = Ast.Data_Balance__c;
     Decimal SMSBal = Ast.SMS_Balance__c;
     Decimal PreBalance = Ast.Prepaid_Balance__c;
     system.debug(PreBalance);
     String PlanId = Ast.Plan__c;
     system.debug(PlanId);
     Plan__c Pln = [Select Data__c,SMS__c,Voice__c from Plan__c where Id =: PlanId];
     Decimal DataPer = Pln.Data__c;
     system.debug(DataPer);
     Decimal SMSPer = Pln.SMS__c;
     system.debug(SMSPer);
     Decimal VoicePer = Pln.Voice__c;
     system.debug(VoicePer);
     Decimal updVoiceBal = PreBalance*(VoicePer/100);
     Decimal updDataBal = PreBalance*(DataPer/100);
     Decimal updSMSBal = PreBalance*(SMSPer/100);
     Ast.Voice_Balance__c = updVoiceBal;
     Ast.Data_Balance__c = updDataBal;
     Ast.SMS_Balance__c = updSMSBal;
     Update Ast;
    }
    
    
}